CCD-2377: Adding PRL service to service_config.json in case-document-am-api
hmcts/ccd-case-document-am-api pull request #511
Opened 2021-12-23 17:00 UTC by rajaram-nagarajan

### JIRA link ###

https://tools.hmcts.net/jira/browse/CCD-2377

### Change description ###

Added PRL services

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-12-23 17:15 UTC, MSancaktutar requested changes
Could we please double check the service would also need Delete? If not, please let's remove Delete.

2021-12-23 17:26 UTC, rajaram-nagarajan commented
> Could we please double check the service would also need Delete? If not, please let's remove Delete.

Removed after confirming with user.

2021-12-23 17:52 UTC, MSancaktutar approved these changes

2021-12-23 18:13 UTC, kaanaktas approved these changes
lgtm

2021-12-24 10:23 UTC, hemantt approved these changes

2021-12-24 13:33 UTC, merged