Ccd 4412 deprecated internal urls
hmcts/ccd-case-document-am-api pull request #650
Opened 2023-04-04 04:01 UTC by kerry-anne-mclaughlin

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the `keep-helm` label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-04-05 09:12 UTC, rajaram-nagarajan requested changes

2023-04-05 09:12 UTC, rajaram-nagarajan commented on Jenkinsfile_CNP
>  env.S2S_URL = "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
@kerry-anne-mclaughlin - This url can be changed as well

2023-04-05 17:04 UTC, rajaram-nagarajan commented on Jenkinsfile_CNP
> +      env.CCD_DATA_STORE_API_BASE_URL = "http://ccd-data-store-api-${environmentOfDependencies}.${environmentOfDependencies}.platform.hmcts.net"
The url should be changed only for aat

2023-04-13 11:28 UTC, JamesCollettCGI approved these changes

2023-04-13 11:34 UTC, aktaskaan approved these changes
It will be good if we can squash the commits as there are 23 of them . Other than that LGTM

2024-03-01 10:51 UTC, closed without merging